### ISSUE TITLE
How to invoke merge option

### ISSUE THREAD

**Issue by brian-chen** [tntim96/JSCover-maven-plugin#11]
JSCover has the option to merge report: http://tntim96.github.io/JSCover/manual/manual.xml#reportMerging

How do I call that option from a pom file if using JSCover-maven-plugin?

thanks!
Brian

**Comment by tntim96** [comment]
There's no option to do this in the maven plugin. The plugin keeps a running total during the run and saves the total at the end.

How would you expect a report merging option to operate?

In the meantime you could call JSCover separately to merge reports.
