### ISSUE TITLE
execution of "jscover-file" stops after configuration

### ISSUE THREAD

**Issue by hedget** [tntim96/JSCover-maven-plugin#12]
hi,

when i run mvn jscover-file:jscover, the execution stops with the following output:

[INFO] --- jscover-file-maven-plugin:1.0.7:jscover (default-cli) @ <project_name> ---

executing it with -X, the execution lists the configuration and stops there.

I am trying to use jscover-file to show the coverage of jasmine tests.

What could be the issue here?

Thank you.

**Comment by tntim96** [comment]
Can you try executing with the `-X` option to reveal the underlying issue? Also, check if a `jscover.log` file has been produced.
