### ISSUE TITLE
Question: JSCover with jasmine custom runner template 

### ISSUE THREAD

**Issue by hedget** [tntim96/JSCover-maven-plugin#13]
Hi,

I would like to use JSCover-maven-plugin to show coverage of jasmine tests. To run the jasmine tests, I use the jasmine-maven-plugin, using a custom runner template(http://searls.github.io/jasmine-maven-plugin/spec-runner-templates.html), which is defined using the "customRunnerTemplate" property of the configuration.

When using the jscover-server-maven-plugin, how do I define the custom runner to use like in the jasmine-maven-plugin? Without specifying this, I get an empty runner page when calling "mvn jscover-server:jscover" without the list of tests.

Thanks.

**Comment by tntim96** [comment]
You can try using [Saga](http://searls.github.io/jasmine-maven-plugin/code-coverage.html). I would have to look at what's needed to make it work with JSCover.

JSCover-maven-plugin runs Jasmine tests with a browser, so is more suited to Jasmine tests requiring DOM interaction.
