### ISSUE TITLE
Running instrumentation over root directory did not work

### ISSUE THREAD

**Issue by dnihar** [tntim96/JSCover-maven-plugin#15]
The directory structure is like,

project
* project-impl
* project-components
* project-util
* project-tools
* project-examples
* project-integrations

`<configuration>`
    `<srcDir>`${project.home}`</srcDir>`
    `<testDirectory>`${project.home}/project-impl/src/test`</testDirectory>`
    `<branchCoverageMinimum>`100`</branchCoverageMinimum>`
    `<functionCoverageMinimum>`100`</functionCoverageMinimum>`
    `<lineCoverageMinimum>`100`</lineCoverageMinimum>`
    `<excludeArgs>`
        `<excludeArg>`--exclude=project-util`</excludeArg>`
        `<excludeArg>`--exclude=project-tools`</excludeArg>`
        `<excludeArg>`--exclude=project-examples`</excludeArg>`
        `<excludeArg>`--exclude=project-integrations`</excludeArg>`
    `</excludeArgs>`
`</configuration>`

So that just didn't work, it recursively created target directories one inside the other and so on with no instrumented code in it and it almost got stuck, I stopped it. If I change the above configuration to, say a specific module, then it works, like srcDir=project-impl

So because of this, I guess I will have to instrument specific modules one by one, into separate directories (because target will get overwritten with next module) and then move those directories under one location.

**Comment by tntim96** [comment]
The file instrumentation copies one directory to a new location (for the plugin the default is `target/reports/jscover-maven`), so I don't think you can specify a `srcDir` that has the `target` directory as a sub-directory (I'm surprised you don't get an error - I'll have to check on this).

What happens if you specify a `reportDir` outside of the project?

**Comment by tntim96** [comment]
> I don't think you can specify a `srcDir` that has the `target` directory as a sub-directory (I'm surprised you don't get an error - I'll have to check on this)

I've uploaded a new snapshot which should detect the `reportDir` being a sub-directory `srcDir`.

> What happens if you specify a `reportDir` outside of the project?

Any luck with that?

**Comment by dnihar** [comment]
well it ran better then before with specifying <reportDir> outside of project directory, but still directory structure all screwed up, so out of say 7 modules, I had it instrument only 2 modules, out of which it successfully created only 1 module, with the other other module being wrong (since it was in excludeArgs) and with wrong directory structure, like 

instrumented/src/ ..(correct)
instrumented/target .. (correct)

instrumented/Users/myself/project-root/module/src (incorrect - this module was excluded)

ok well, so I guess the only way here is what am trying right now, which is instrumenting modules which I want individually and then running some maven file tasks to get them under one location.

odd though, about this limitation, since rarely we would just have one monolithic javascript-module, so it's natural to say specify a project-root and include/exclude modules in it.

**Comment by tntim96** [comment]
OK. I'm not sure exactly how to help, but if you can demonstrate what you think should happen I'm happy to add functionality. A sample github project would help.

**Comment by dnihar** [comment]
Thanks. Well, all I was saying is, it would be awesome to have one shot instrumentation for all the needed modules, like,

project
    project-components
    project-tools
    project-integration
    project-framework

So for something like that, we could just use srcDir=project and then excludeArgs=project-integration,project-tools ..so then the instrumentation just runs over everything else (project-components,project-framework).

Since I was exploring this anyways, I have already done a work around. I still think the above is nice to have.

**1. separate question**
Now, I am instrumenting modules individually from the respective module's pom.xml and then having it generate the instrumented resources as follows-

``project/target``
    ``project-components``
        <jscover.log, jscoverage.html, etc..>
    ``project-framework``
        <jscover.log, jscoverage.html, etc..>

Is there a way to unify the coverage for the above 2 modules? I guess what I need is what's mentioned in JSCover manual,
--merge	N/A	Merge coverage reports from REPORT-DIR1 REPORT-DIR2 REPORT-DIR3... to DEST-DIR 
How to do that though, using this file based plugin.
           
**2. separate question**
Do I still need to use ``<version>``1.0.16-SNAPSHOT``</version>``
Or is it's now available in maven repo?

**Comment by tntim96** [comment]
I haven't implemented merge into the plugin but am open to suggestions.

I'll try to implement the merge mojo and release if I can get it working to your satisfaction.

**Comment by tntim96** [comment]
I've added a target `jscover-report:merge` - can you give that a try?

**Comment by dnihar** [comment]
I guess it worked, I did not error out, I still don't have the UI up to confirm, this is how I used it,
```javascript
<dependency>
    <groupId>com.github.tntim96</groupId>
    <artifactId>jscover-report-maven-plugin</artifactId>
    <version>1.0.16-SNAPSHOT</version>
    <executions>
        <execution>
            <id>merge-coverage-reports</id>
            <phase>disabled</phase>
            <goals>
                <goal>merge</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
       <dir>/Users/myself/project/${project.artifactId}/target</dir>
       <dir>/Users/myself/project/${project.artifactId}/target</dir>
    </configuration>
</dependency>
```

So for the UI, even we use Jenkins, so I wanted to know if/how I could use format=COBERTURAXML we already have cobertura plugin on jenkins for java code coverage.

**Comment by tntim96** [comment]
I've added a format goal, and there's a sample in [JSCover-Samples's pom.xml](https://github.com/tntim96/JSCover-samples/blob/master/pom.xml).

**Comment by dnihar** [comment]
Thanks, I will try this.

**Comment by dnihar** [comment]
Thanks, that worked. It generated cobertura-coverage.xml and jscover.lcov.. I still have to set it up on Jenkins etc. But good to close out this issue. 

Also, before I integrate my code, I will need to get rid of snapshots, you think you can put these enhancements (goals 'instrument', report-plugin ('merge', 'format')) into maven release candidate?

**Comment by tntim96** [comment]
Sure - just wanted to confirm it behaves as expected for you first. Might need a day or two to release.

**Comment by dnihar** [comment]
Works. Thanks.

**Comment by tntim96** [comment]
K - release is done

**Comment by dnihar** [comment]
I removed the sonatype snapshot pluginrepositories and updated dependencies to,
```javascript
<dependency>
    <groupId>com.github.tntim96</groupId>
    <artifactId>jscover-file-maven-plugin</artifactId>
    <version>1.0.17-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>com.github.tntim96</groupId>
    <artifactId>jscover-report-maven-plugin</artifactId>
    <version>1.0.17-SNAPSHOT</version>
</dependency>
```
It's errors out saying,
[WARNING] The POM for com.github.tntim96:jscover-file-maven-plugin:jar:1.0.17-SNAPSHOT is missing, no dependency information available
[ERROR] Plugin com.github.tntim96:jscover-file-maven-plugin:1.0.17-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact com.github.tntim96:jscover-file-maven-plugin:jar:1.0.17-SNAPSHOT 

Also tried mvn clean install -U

**Comment by dnihar** [comment]
Ok, I guess I still need to use 1.0.16 for both. That worked.

**Comment by tntim96** [comment]
Yes 1.0.16 is the new release with the changes you want. After doing a release I always bump the version to the next snapshot - but 1.0.17-SNAPSHOT doesn't have anything extra in it yet.
