### ISSUE TITLE
Cannot specify proxy for webclient

### ISSUE THREAD

**Issue by chapmanc** [tntim96/JSCover-maven-plugin#17]
Cannot pass proxy to phantomjs as https://github.com/tntim96/JSCover-maven-plugin/blob/d4c6064ef9cb266a95cddbf9c4324d414029b2cf/plugin-parent/common/src/main/java/jscover/maven/JSCoverMojo.java#L99  do not parse any system properties.

**Comment by tntim96** [comment]
What's the use case? Just asking because I add tests, and might as well make it match your scenario if possible.

**Comment by chapmanc** [comment]
We have our maven plugin operating in an environment with a proxy. In the jasmine maven plugin you can pass cli options to phantomjs  https://searls.github.io/jasmine-maven-plugin/webdriver-customization.html When we run our tests they work fine but running jscover with the maven plugin we can't pass the proxy so our tests which require external resources cant load. 

Ideally it would be best to be able to do the same thing with the jasmine maven plugin

**Comment by tntim96** [comment]
Can you test if the latest snapshot works for you? Sample configuration:
```XML
    <httpProxy>localhost:3128</httpProxy>
```

**Comment by chapmanc** [comment]
Works great. Thanks very much!

**Comment by chapmanc** [comment]
Any news on when this will be pushed into a  release? The Retest tag can also be removed @tntim96

**Comment by tntim96** [comment]
I'll release now and confirm when it's in Maven.

**Comment by tntim96** [comment]
K - should be there now
